### ISSUE TITLE
运行报错：sqlite3.OperationalError: no such table: Friends

### ISSUE THREAD

**Issue by Grieaf** [roadwide/qqmessageoutput#16]
``Traceback (most recent call last):
  File "D:\admin1\Downloads\qqmessageoutput-master\qqmessageoutput-master\q.py", line 127, in <module>
    q.getAllMyFriends()
  File "D:\admin1\Downloads\qqmessageoutput-master\qqmessageoutput-master\q.py", line 100, in getAllMyFriends
    cursor = self.c.execute(execute)
sqlite3.OperationalError: no such table: Friends
``
想问一下这个是怎么回事啊

**Comment by lotustalk** [comment]
新版qq使用了新架构,原本的工具都失效了,相当于启用了新的一个数据库

**Comment by sli263955-prog** [comment]
> 新版qq使用了新的架构，不知什么工具都失效了，实际上启用了新的一个数据库

新版指的是哪年以后的？我想恢复旧版的可以嘛？谢谢你
