### ISSUE TITLE
前面的聊天记录都打印在屏幕上了 但是后面显示数据为空是怎么回事？

### ISSUE THREAD

**Issue by chainCAI** [roadwide/qqmessageoutput#8]
Traceback (most recent call last):
  File "D:\D桌面\q.py", line 127, in <module>
    q.output(yourfriendqq, mode)
  File "D:\D桌面\q.py", line 80, in output
    allmsg = self.message(num, mode)
  File "D:\D桌面\q.py", line 66, in message
    msg = self.fix(msgdata, 0)
  File "D:\D桌面\q.py", line 20, in fix
    for i in range(0, len(data)):
TypeError: object of type 'NoneType' has no len()

**Comment by roadwide** [comment]
前面后面是什么意思

**Comment by chainCAI** [comment]
就是开始的运行这个程序的时候 聊天记录都能正常加载出来 后面就开始报错说数据类型错误

**Comment by roadwide** [comment]
没遇到过，你可以在具体出错的地方调试一下。
